(function () {
'use strict';

angular.module('ShoppingListComponentApp', [])
.controller('ShoppingListController', ShoppingListController)
.factory('ShoppingListFactory', ShoppingListFactory)
.component('shoppingList', {
  templateUrl: 'shoppingList.html',
  controller: ShoppingListComponentController,
  bindings: {
    items: '<',
    myTitle: '@title',
    onRemove: '&'
  }
});

ShoppingListComponentController.$inject = ['$scope','$element']
function ShoppingListComponentController($scope,$element) {
  var ctrl = this;

  ctrl.cookiesInList = function () {
    for (var i = 0; i < ctrl.items.length; i++) {
      var name = ctrl.items[i].name;
      if (name.toLowerCase().indexOf("cookie") !== -1) {
        return true;
      }
    }

    return false;
  };

  ctrl.remove = function (myIndex){
    ctrl.onRemove({index: myIndex});//this is the reference for the remove item function passed in from the main controller; myIndex comes from the component $index
  };

  //lifecycle methods for components
  ctrl.$onInit = function (){
    console.log("we are $onInit()");
  };
  ctrl.$onChanges = function (changeObj){
    console.log(changeObj);
  };
  ctrl.$postLink = function (){//postLink does not have access to the scope, element, attributes, controller and transclude arguments; need to inject $scope and $element
    $scope.$watch('$ctrl.cookiesInList()', function (newValue, oldValue){//when watching it needs the controller as syntax which in this case is the autogenerated $ctrl for a component without controllerAs property
      console.log($element);
      if (newValue === true) {
        var warningElem = $element.find('div.error');
        warningElem.slideDown(900);
      } else {
        var warningElem = $element.find('div.error');
        warningElem.slideUp(900);
      }
    });
  };
}


ShoppingListController.$inject = ['ShoppingListFactory'];
function ShoppingListController(ShoppingListFactory) {
  var list = this;

  // Use factory to create new shopping list service
  var shoppingList = ShoppingListFactory();

  list.items = shoppingList.getItems();
  var origTitle = "Shopping List #1";
  list.title = origTitle + " (" + list.items.length + " items )";

  list.itemName = "";
  list.itemQuantity = "";

  list.addItem = function () {
    shoppingList.addItem(list.itemName, list.itemQuantity);
    list.title = origTitle + " (" + list.items.length + " items )";
  }

  list.removeItem = function (itemIndex) {
    console.log("'this' is: ", this);
    this.lastRemoved = "Last item removed was " + this.items[itemIndex].name;
    shoppingList.removeItem(itemIndex);
    this.title = origTitle + " (" + list.items.length + " items )";
  };
}


// If not specified, maxItems assumed unlimited
function ShoppingListService(maxItems) {
  var service = this;

  // List of shopping items
  var items = [];

  service.addItem = function (itemName, quantity) {
    if ((maxItems === undefined) ||
        (maxItems !== undefined) && (items.length < maxItems)) {
      var item = {
        name: itemName,
        quantity: quantity
      };
      items.push(item);
    }
    else {
      throw new Error("Max items (" + maxItems + ") reached.");
    }
  };

  service.removeItem = function (itemIndex) {
    items.splice(itemIndex, 1);
  };

  service.getItems = function () {
    return items;
  };
}


function ShoppingListFactory() {
  var factory = function (maxItems) {
    return new ShoppingListService(maxItems);
  };

  return factory;
}

})();
